# This action is two steps, the first will use the actions/hello-world-javascript-action@v1.1 public action.
# The second action will reference the first one, and get the time output and echo it as part of the console log.
name: Actions Workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
          pwd
          ls
      - name: Simple JavaScript Action
        id: greet
        uses: actions/hello-world-javascript-action@v1.1
        with:
          who-to-greet: Casey
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"