# This action is two steps, the first will use the actions/hello-world-javascript-action@v1.1 public action.
# The second action will reference the first one, and get the time output and echo it as part of the console log.
name: Actions Workflow

on:
  schedule:
    - cron: "0/5 * * * *"
  pull_request:
    types: [closed]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
          pwd
          ls -a
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - name: List Files After Checkout
        run: |
          pwd
          ls -a
      - name: Simple JavaScript Action
        id: greet
        uses: actions/hello-world-javascript-action@v1.1
        with:
          who-to-greet: Casey
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"